import dynamic from "next/dynamic";
import Head from "next/head";

const MetaMaskCard = dynamic(() => import('./components/MetaMaskCard'), { ssr: false })

const Home = () => {

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MetaMaskCard />
    </div>
  );
};

export default Home;
