import { Grid } from "@mui/material";
import dynamic from "next/dynamic";
import Head from "next/head";
import { useMoralis } from "react-moralis";
import { DEFAULT_CHAIN_HEX } from "../../config/chainsConfig";
import Survey from "./components/survey";

const MetaMaskCard = dynamic(() => import('./components/metamask/MetaMaskCard'), { ssr: false })

const Home = () => {
  const {
    isAuthenticated,
    chainId
  } = useMoralis();

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MetaMaskCard />

      {isAuthenticated && chainId === DEFAULT_CHAIN_HEX && (
        <Grid container justifyContent="center">
          <Survey />
        </Grid>
      )}
    </div>
  );
};

export default Home;
